"""add dialog_messages table

Revision ID: 6a116c1781a1
Revises: 3322351eeac7
Create Date: 2026-09-01 16:58:42.016736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a116c1781a1'
down_revision: Union[str, Sequence[str], None] = '3322351eeac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialog_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dialog_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dialog_id'], ['dialogs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dialog_messages_dialog_id_created_at', 'dialog_messages', ['dialog_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
    # Manually adjusted post-autogenerate (found via /aif-review):
    # ondelete='CASCADE' on the FK, plus the (dialog_id, created_at) index
    # for list_by_dialog. This revision was not applied anywhere else yet,
    # so it was corrected in place rather than via a follow-up migration.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dialog_messages')
    # ### end Alembic commands ###
