"""add extracted_text and parse_status to files

Revision ID: 95d281737753
Revises: 720a9a7ef396
Create Date: 2026-09-06 12:06:08.151706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d281737753'
down_revision: Union[str, Sequence[str], None] = '720a9a7ef396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column(
        'files',
        sa.Column(
            'parse_status',
            sa.String(),
            nullable=False,
            # Manually adjusted post-autogenerate: `parse_status` is NOT
            # NULL with no application-level default, but pre-existing
            # `files` rows (from before this migration) need a value to
            # backfill — dropped right after. The ORM model never
            # declares a server_default; new rows always get an explicit
            # `parse_status` from `FileService.upload_file`.
            server_default='skipped',
        ),
    )
    op.alter_column('files', 'parse_status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'parse_status')
    op.drop_column('files', 'extracted_text')
    # ### end Alembic commands ###
